version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: disney_demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
